default['openvpn']['device'] = "tap0"
default['openvpn']['proto'] = "udp"
default['openvpn']['resolv-retry'] = "infinite"
default['openvpn']['user'] = "nobody"
default['openvpn']['group'] = "nobody"
default['openvpn']['cipher'] = "AES-256-CBC"
default['openvpn']['verb'] = "3"
